language: objective-c
osx_image: xcode10.2

before_script:
    - carthage bootstrap

script:
    - set -o pipefail && xcodebuild -project RileyLink.xcodeproj -scheme RileyLink build -destination 'name=iPhone SE' test | xcpretty
